apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iampolicies.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - providerRef
                - policy
              properties:
                providerRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                policy:
                  type: object
                  description: IAM policy document
                  required:
                    - version
                    - statement
                  properties:
                    version:
                      type: string
                      default: "2012-10-17"
                    statement:
                      type: array
                      items:
                        type: object
                        required: [effect, action, resource]
                        properties:
                          sid:
                            type: string
                          effect:
                            type: string
                            enum: [Allow, Deny]
                          principal:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                          action:
                            type: array
                            items:
                              type: string
                          resource:
                            type: array
                            items:
                              type: string
                          condition:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                tags:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                policyArn:
                  type: string
                  description: Policy ARN (if available from provider)
                applied:
                  type: boolean
                  description: Whether policy has been applied
                attachedUsers:
                  type: array
                  items:
                    type: string
                  description: List of users this policy is attached to
                lastSyncTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      observedGeneration:
                        type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: iampolicies
    singular: iampolicy
    kind: IAMPolicy
    shortNames:
      - iamp

