apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - type
                - endpoint
                - region
                - auth
              properties:
                type:
                  type: string
                  enum: [wasabi]
                  default: wasabi
                  description: Wasabi S3 provider type
                endpoint:
                  type: string
                  format: uri
                  description: Provider API endpoint URL
                region:
                  type: string
                  description: Provider region
                auth:
                  type: object
                  required:
                    - accessKeySecretRef
                    - secretKeySecretRef
                  properties:
                    accessKeySecretRef:
                      type: object
                      required: [name]
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                          default: access-key
                        namespace:
                          type: string
                    secretKeySecretRef:
                      type: object
                      required: [name]
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                          default: secret-key
                        namespace:
                          type: string
                    sessionTokenSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                          default: session-token
                        namespace:
                          type: string
                tls:
                  type: object
                  properties:
                    insecureSkipVerify:
                      type: boolean
                      default: false
                    caCertSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                          default: ca.crt
                pathStyle:
                  type: boolean
                  default: true
                iamEndpoint:
                  type: string
                  format: uri
                  description: IAM endpoint URL (required for user management, e.g., https://iam.wasabisys.com)
                iamRegion:
                  type: string
                  description: IAM region for IAM operations (optional, defaults to us-east-1)
                retry:
                  type: object
                  properties:
                    maxAttempts:
                      type: integer
                      default: 3
                      minimum: 1
                      maximum: 10
                    backoffStrategy:
                      type: string
                      enum: [exponential, linear]
                      default: exponential
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                connected:
                  type: boolean
                lastConnectTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      observedGeneration:
                        type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: providers
    singular: provider
    kind: Provider
    shortNames:
      - s3prov

