---
apiVersion: s3.cloud37.dev/v1alpha1
kind: Bucket
metadata:
  name: operator-testing
  namespace: s3-provider-operator
spec:
  providerRef:
    name: wasabi-eu-central-2
  name: operator-testing
  autoManage:
    enabled: true
    userName: operator-testing
    accessLevel: readwrite  # readonly, readwrite, or full
    rotation:
      enabled: true
      intervalDays: 90
      previousKeysRetentionDays: 7
  versioning:
    enabled: true
  encryption:
    enabled: true
    algorithm: AES256

---
# That's it! The operator will automatically create:
# - User: my-app-storage-user
# - BucketPolicy: grants the user access to the bucket
# - AccessKey: creates keys for the user
# - Secret: my-app-storage-accesskey-credentials

# To get credentials:
# kubectl get secret my-app-storage-accesskey-credentials \
#   -o jsonpath='{.data.access-key-id}' | base64 -d
# kubectl get secret my-app-storage-accesskey-credentials \
#   -o jsonpath='{.data.secret-access-key}' | base64 -d

