apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wasabi-credentials
  namespace: s3-provider-operator
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: wasabi-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: access-key
      remoteRef:
        key: kv/data/s3-provider-operator/wasabi-credentials
        property: access-key
    - secretKey: secret-key
      remoteRef:
        key: kv/data/s3-provider-operator/wasabi-credentials
        property: secret-key
---
apiVersion: s3.cloud37.dev/v1alpha1
kind: Provider
metadata:
  name: wasabi-eu-central-2
  namespace: s3-provider-operator
spec:
  type: wasabi
  endpoint: https://s3.eu-central-2.wasabisys.com
  iamEndpoint: https://iam.wasabisys.com
  iamRegion: us-east-1  # Wasabi IAM requires us-east-1 region
  region: eu-central-2
  auth:
    accessKeySecretRef:
      name: wasabi-credentials
      key: access-key
    secretKeySecretRef:
      name: wasabi-credentials
      key: secret-key
  pathStyle: true
  retry:
    maxAttempts: 3
    backoffStrategy: exponential

