apiVersion: s3.cloud37.dev/v1alpha1
kind: User
metadata:
  name: my-app-user
spec:
  providerRef:
    name: wasabi-us-east-1
  name: my-app-user
  policy:
    version: "2012-10-17"
    statement:
      - effect: Allow
        action:
          - s3:GetObject
          - s3:PutObject
        resource:
          - "arn:aws:s3:::my-bucket/*"
  tags:
    Environment: production
    Application: my-app

