apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesskeys.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - providerRef
              properties:
                providerRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                displayName:
                  type: string
                policy:
                  type: object
                tags:
                  type: object
                  additionalProperties:
                    type: string
                rotate:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    intervalDays:
                      type: integer
                      default: 90
                      minimum: 1
                      maximum: 365
                    previousKeysRetentionDays:
                      type: integer
                      default: 7
                      minimum: 0
                      maximum: 30
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                accessKeyId:
                  type: string
                created:
                  type: boolean
                lastRotateTime:
                  type: string
                  format: date-time
                nextRotateTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: accesskeys
    singular: accesskey
    kind: AccessKey
    shortNames:
      - s3key

