apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buckets.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - providerRef
                - name
              properties:
                providerRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                autoManage:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                      description: Automatically create User, BucketPolicy, and AccessKey
                    userName:
                      type: string
                      description: Name for the auto-created user (defaults to bucket name)
                    accessLevel:
                      type: string
                      enum: [readonly, readwrite, full]
                      default: readwrite
                      description: Access level for the auto-created user
                    rotation:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        intervalDays:
                          type: integer
                          default: 90
                          minimum: 1
                          maximum: 365
                        previousKeysRetentionDays:
                          type: integer
                          default: 7
                          minimum: 0
                          maximum: 30
                  description: Automatic resource management configuration
                name:
                  type: string
                  pattern: '^[a-z0-9][a-z0-9\-\.]{1,61}[a-z0-9]$'
                region:
                  type: string
                versioning:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    mfaDelete:
                      type: boolean
                      default: false
                encryption:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    algorithm:
                      type: string
                      enum: [AES256, aws:kms]
                      default: AES256
                    kmsKeyId:
                      type: string
                publicAccess:
                  type: object
                  properties:
                    blockPublicAcls:
                      type: boolean
                      default: true
                    blockPublicPolicy:
                      type: boolean
                      default: true
                    ignorePublicAcls:
                      type: boolean
                      default: true
                    restrictPublicBuckets:
                      type: boolean
                      default: true
                lifecycle:
                  type: object
                  properties:
                    rules:
                      type: array
                      items:
                        type: object
                        required: [id]
                        properties:
                          id:
                            type: string
                          status:
                            type: string
                            enum: [Enabled, Disabled]
                            default: Enabled
                          prefix:
                            type: string
                          expiration:
                            type: object
                            properties:
                              days:
                                type: integer
                                minimum: 1
                              date:
                                type: string
                                format: date
                          transitions:
                            type: array
                            items:
                              type: object
                              required: [days, storageClass]
                              properties:
                                days:
                                  type: integer
                                  minimum: 1
                                storageClass:
                                  type: string
                cors:
                  type: object
                  properties:
                    rules:
                      type: array
                      items:
                        type: object
                        required: [allowedOrigins, allowedMethods]
                        properties:
                          allowedOrigins:
                            type: array
                            items:
                              type: string
                          allowedMethods:
                            type: array
                            items:
                              type: string
                              enum: [GET, POST, PUT, DELETE, HEAD]
                          allowedHeaders:
                            type: array
                            items:
                              type: string
                          exposedHeaders:
                            type: array
                            items:
                              type: string
                          maxAgeSeconds:
                            type: integer
                            default: 3600
                            minimum: 0
                tagging:
                  type: object
                  properties:
                    tags:
                      type: object
                      additionalProperties:
                        type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                bucketName:
                  type: string
                arn:
                  type: string
                exists:
                  type: boolean
                lastSyncTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      observedGeneration:
                        type: integer
                credentialsSecret:
                  type: string
                  description: Name of the secret containing bucket access credentials
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: buckets
    singular: bucket
    kind: Bucket
    shortNames:
      - s3bkt

