apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bucketpolicies.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - bucketRef
                - policy
              properties:
                bucketRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                policy:
                  type: object
                  required: [version, statement]
                  properties:
                    version:
                      type: string
                      default: "2012-10-17"
                    statement:
                      type: array
                      items:
                        type: object
                        required: [effect, principal, action, resource]
                        properties:
                          sid:
                            type: string
                          effect:
                            type: string
                            enum: [Allow, Deny]
                          principal:
                            oneOf:
                              - type: string
                              - type: object
                          action:
                            oneOf:
                              - type: string
                              - type: array
                                items:
                                  type: string
                          resource:
                            oneOf:
                              - type: string
                              - type: array
                                items:
                                  type: string
                          condition:
                            type: object
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                applied:
                  type: boolean
                lastSyncTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: bucketpolicies
    singular: bucketpolicy
    kind: BucketPolicy
    shortNames:
      - s3policy

