apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.s3.cloud37.dev
spec:
  group: s3.cloud37.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - providerRef
                - name
              properties:
                providerRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                name:
                  type: string
                  description: User name
                policy:
                  type: object
                  description: Inline IAM policy for the user
                tags:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                userId:
                  type: string
                  description: User ID (generated by provider)
                created:
                  type: boolean
                lastSyncTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      observedGeneration:
                        type: integer
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
      - s3user

