name: Setup GitHub Pages

on:
  workflow_dispatch:
    inputs:
      create_gh_pages:
        description: 'Create gh-pages branch for Helm repository'
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create gh-pages branch
        run: |
          # Check if gh-pages branch already exists
          if git ls-remote --heads origin gh-pages | grep gh-pages > /dev/null; then
            echo "gh-pages branch already exists"
            git checkout gh-pages
            git reset --hard origin/gh-pages
          else
            echo "Creating new gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit for GitHub Pages"
          fi
          git push origin gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Create initial index.yaml
        run: |
          mkdir -p charts
          cat > index.yaml << 'EOF'
          apiVersion: v1
          entries: {}
          generated: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          EOF
          git add .
          git commit -m "Add initial Helm repository index"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
